// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.core.Core;
import myfirstmodule.pdf.Position;
import myfirstmodule.pdf.OrgChartParser;
import myfirstmodule.pdf.OrgChartRenderer;
import java.util.Base64;

public class PDFRenderer extends CustomJavaAction<java.lang.String>
{
	private java.lang.String OrgJSON_TR;
	private java.lang.String OrgJSON_EN;
	private java.lang.String titleTR;
	private java.lang.String totalNormLabelTR;
	private java.lang.String preparedByTR;
	private java.lang.String docDateTR;
	private java.lang.String lastUpdateTR;
	private java.lang.String imageUrlTR;
	private java.lang.String titleEN;
	private java.lang.String totalNormLabelEN;
	private java.lang.String preparedByEN;
	private java.lang.String docDateEN;
	private java.lang.String lastUpdateEN;
	private java.lang.String imageUrlEN;

	public PDFRenderer(IContext context, java.lang.String OrgJSON_TR, java.lang.String OrgJSON_EN, java.lang.String titleTR, java.lang.String totalNormLabelTR, java.lang.String preparedByTR, java.lang.String docDateTR, java.lang.String lastUpdateTR, java.lang.String imageUrlTR, java.lang.String titleEN, java.lang.String totalNormLabelEN, java.lang.String preparedByEN, java.lang.String docDateEN, java.lang.String lastUpdateEN, java.lang.String imageUrlEN)
	{
		super(context);
		this.OrgJSON_TR = OrgJSON_TR;
		this.OrgJSON_EN = OrgJSON_EN;
		this.titleTR = titleTR;
		this.totalNormLabelTR = totalNormLabelTR;
		this.preparedByTR = preparedByTR;
		this.docDateTR = docDateTR;
		this.lastUpdateTR = lastUpdateTR;
		this.imageUrlTR = imageUrlTR;
		this.titleEN = titleEN;
		this.totalNormLabelEN = totalNormLabelEN;
		this.preparedByEN = preparedByEN;
		this.docDateEN = docDateEN;
		this.lastUpdateEN = lastUpdateEN;
		this.imageUrlEN = imageUrlEN;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			Core.getLogger("PDFRenderer").info("Starting PDF generation with provided JSON data...");
			
			// Use parameters instead of dummy data
			String jsonTR = this.OrgJSON_TR;
			String jsonEN = this.OrgJSON_EN;
			
			// Legacy dummy fallback for testing (remove in production)
			if ((jsonTR == null || jsonTR.trim().isEmpty()) && (jsonEN == null || jsonEN.trim().isEmpty())) {
				Core.getLogger("PDFRenderer").warn("No JSON data provided, using dummy test data...");
				// Flat array structure - each position has direct children in Positions array (not recursive nested)
				// HierarchyCode is used to build the tree structure
				jsonTR = "["
			+ "{\"PositionID\": 1, \"PositionName\": \"Icra Kurulu Baskani ve Genel Mudur\", \"Norm\": \"1\", \"TitleCode\": \"9\", \"HierarchyCode\": \"/1/\", \"ParentHierarchyCode\": \"\", \"Positions\": ["
			+ "  {\"PositionID\": 2, \"PositionName\": \"Bilgi Teknolojileri ve Dijital Donusum Direktoru\", \"Norm\": \"1\", \"TitleCode\": \"12\", \"HierarchyCode\": \"/1/2/\", \"ParentHierarchyCode\": \"/1/\", \"Positions\": []},"
			+ "  {\"PositionID\": 3, \"PositionName\": \"Mali Isler ve Finans Yonetimi Direktoru\", \"Norm\": \"1\", \"TitleCode\": \"12\", \"HierarchyCode\": \"/1/3/\", \"ParentHierarchyCode\": \"/1/\", \"Positions\": []},"
			+ "  {\"PositionID\": 4, \"PositionName\": \"Operasyon ve Surecler Yonetimi Direktoru\", \"Norm\": \"1\", \"TitleCode\": \"12\", \"HierarchyCode\": \"/1/4/\", \"ParentHierarchyCode\": \"/1/\", \"Positions\": []},"
			+ "  {\"PositionID\": 5, \"PositionName\": \"Insan Kaynaklari ve Kurumsal Gelisim Direktoru\", \"Norm\": \"1\", \"TitleCode\": \"12\", \"HierarchyCode\": \"/1/5/\", \"ParentHierarchyCode\": \"/1/\", \"Positions\": []}"
			+ "]},"
			+ "{\"PositionID\": 2, \"PositionName\": \"Bilgi Teknolojileri ve Dijital Donusum Direktoru\", \"Norm\": \"1\", \"TitleCode\": \"12\", \"HierarchyCode\": \"/1/2/\", \"ParentHierarchyCode\": \"/1/\", \"Positions\": ["
			+ "  {\"PositionID\": 10, \"PositionName\": \"Kurumsal Yazilim Gelistirme ve Uygulama Muduru\", \"Norm\": \"1\", \"TitleCode\": \"13\", \"HierarchyCode\": \"/1/2/10/\", \"ParentHierarchyCode\": \"/1/2/\", \"Positions\": []},"
			+ "  {\"PositionID\": 11, \"PositionName\": \"Sistem Altyapisi ve Bulut Teknolojileri Muduru\", \"Norm\": \"1\", \"TitleCode\": \"13\", \"HierarchyCode\": \"/1/2/11/\", \"ParentHierarchyCode\": \"/1/2/\", \"Positions\": []},"
			+ "  {\"PositionID\": 12, \"PositionName\": \"Bilgi Guvenligi ve Siber Savunma Muduru\", \"Norm\": \"1\", \"TitleCode\": \"13\", \"HierarchyCode\": \"/1/2/12/\", \"ParentHierarchyCode\": \"/1/2/\", \"Positions\": []},"
			+ "  {\"PositionID\": 13, \"PositionName\": \"Veri Analizi ve Is Zekasi Sistemleri Muduru\", \"Norm\": \"1\", \"TitleCode\": \"13\", \"HierarchyCode\": \"/1/2/13/\", \"ParentHierarchyCode\": \"/1/2/\", \"Positions\": []}"
			+ "]},"
			+ "{\"PositionID\": 10, \"PositionName\": \"Kurumsal Yazilim Gelistirme ve Uygulama Muduru\", \"Norm\": \"1\", \"TitleCode\": \"13\", \"HierarchyCode\": \"/1/2/10/\", \"ParentHierarchyCode\": \"/1/2/\", \"Positions\": ["
			+ "  {\"PositionID\": 20, \"PositionName\": \"Backend Sistemler ve API Gelistirme Takimi\", \"Norm\": \"1\", \"TitleCode\": \"40\", \"HierarchyCode\": \"/1/2/10/20/\", \"ParentHierarchyCode\": \"/1/2/10/\", \"Positions\": []},"
			+ "  {\"PositionID\": 21, \"PositionName\": \"Frontend ve Kullanici Deneyimi Takimi\", \"Norm\": \"1\", \"TitleCode\": \"40\", \"HierarchyCode\": \"/1/2/10/21/\", \"ParentHierarchyCode\": \"/1/2/10/\", \"Positions\": []},"
			+ "  {\"PositionID\": 22, \"PositionName\": \"Mobil Uygulama Gelistirme ve Platform Takimi\", \"Norm\": \"1\", \"TitleCode\": \"40\", \"HierarchyCode\": \"/1/2/10/22/\", \"ParentHierarchyCode\": \"/1/2/10/\", \"Positions\": []}"
			+ "]},"
			+ "{\"PositionID\": 20, \"PositionName\": \"Backend Sistemler ve API Gelistirme Takimi\", \"Norm\": \"1\", \"TitleCode\": \"40\", \"HierarchyCode\": \"/1/2/10/20/\", \"ParentHierarchyCode\": \"/1/2/10/\", \"Positions\": ["
			+ "  {\"PositionID\": 100, \"PositionName\": \"Kıdemli Backend Yazilim Gelistirme Uzmani\", \"Norm\": \"4\", \"TitleCode\": \"40\", \"HierarchyCode\": \"/1/2/10/20/100/\", \"ParentHierarchyCode\": \"/1/2/10/20/\", \"Positions\": []},"
			+ "  {\"PositionID\": 101, \"PositionName\": \"Junior Backend Yazilim Gelistirme Uzmani\", \"Norm\": \"6\", \"TitleCode\": \"40\", \"HierarchyCode\": \"/1/2/10/20/101/\", \"ParentHierarchyCode\": \"/1/2/10/20/\", \"Positions\": []},"
			+ "  {\"PositionID\": 102, \"PositionName\": \"DevOps ve Surekli Entegrasyon Uzmani\", \"Norm\": \"3\", \"TitleCode\": \"40\", \"HierarchyCode\": \"/1/2/10/20/102/\", \"ParentHierarchyCode\": \"/1/2/10/20/\", \"Positions\": []}"
			+ "]},"
			+ "{\"PositionID\": 21, \"PositionName\": \"Frontend ve Kullanici Deneyimi Takimi\", \"Norm\": \"1\", \"TitleCode\": \"40\", \"HierarchyCode\": \"/1/2/10/21/\", \"ParentHierarchyCode\": \"/1/2/10/\", \"Positions\": ["
			+ "  {\"PositionID\": 103, \"PositionName\": \"Kıdemli Frontend Gelistirici ve React Uzmani\", \"Norm\": \"3\", \"TitleCode\": \"40\", \"HierarchyCode\": \"/1/2/10/21/103/\", \"ParentHierarchyCode\": \"/1/2/10/21/\", \"Positions\": []},"
			+ "  {\"PositionID\": 104, \"PositionName\": \"Kullanici Arayuzu ve Deneyim Tasarim Uzmani\", \"Norm\": \"2\", \"TitleCode\": \"40\", \"HierarchyCode\": \"/1/2/10/21/104/\", \"ParentHierarchyCode\": \"/1/2/10/21/\", \"Positions\": []},"
			+ "  {\"PositionID\": 105, \"PositionName\": \"Erisebilirlik ve Performans Optimizasyonu Uzmani\", \"Norm\": \"2\", \"TitleCode\": \"40\", \"HierarchyCode\": \"/1/2/10/21/105/\", \"ParentHierarchyCode\": \"/1/2/10/21/\", \"Positions\": []}"
			+ "]},"
			+ "{\"PositionID\": 11, \"PositionName\": \"Sistem Altyapisi ve Bulut Teknolojileri Muduru\", \"Norm\": \"1\", \"TitleCode\": \"13\", \"HierarchyCode\": \"/1/2/11/\", \"ParentHierarchyCode\": \"/1/2/\", \"Positions\": ["
			+ "  {\"PositionID\": 23, \"PositionName\": \"Ag Altyapisi ve Iletisim Sistemleri Uzmani\", \"Norm\": \"5\", \"TitleCode\": \"39\", \"HierarchyCode\": \"/1/2/11/23/\", \"ParentHierarchyCode\": \"/1/2/11/\", \"Positions\": []},"
			+ "  {\"PositionID\": 24, \"PositionName\": \"Bulut Mimarisi ve Azure Platform Uzmani\", \"Norm\": \"4\", \"TitleCode\": \"39\", \"HierarchyCode\": \"/1/2/11/24/\", \"ParentHierarchyCode\": \"/1/2/11/\", \"Positions\": []},"
			+ "  {\"PositionID\": 25, \"PositionName\": \"Veritabani Yonetimi ve Optimizasyon Uzmani\", \"Norm\": \"4\", \"TitleCode\": \"39\", \"HierarchyCode\": \"/1/2/11/25/\", \"ParentHierarchyCode\": \"/1/2/11/\", \"Positions\": []},"
			+ "  {\"PositionID\": 26, \"PositionName\": \"Sunucu ve Sanallaştirma Teknolojileri Uzmani\", \"Norm\": \"3\", \"TitleCode\": \"39\", \"HierarchyCode\": \"/1/2/11/26/\", \"ParentHierarchyCode\": \"/1/2/11/\", \"Positions\": []}"
			+ "]},"
			+ "{\"PositionID\": 3, \"PositionName\": \"Mali Isler ve Finans Yonetimi Direktoru\", \"Norm\": \"1\", \"TitleCode\": \"12\", \"HierarchyCode\": \"/1/3/\", \"ParentHierarchyCode\": \"/1/\", \"Positions\": ["
			+ "  {\"PositionID\": 14, \"PositionName\": \"Genel Muhasebe ve Raporlama Muduru\", \"Norm\": \"1\", \"TitleCode\": \"11\", \"HierarchyCode\": \"/1/3/14/\", \"ParentHierarchyCode\": \"/1/3/\", \"Positions\": []},"
			+ "  {\"PositionID\": 15, \"PositionName\": \"Odeme Sistemleri ve Nakit Yonetimi Muduru\", \"Norm\": \"1\", \"TitleCode\": \"11\", \"HierarchyCode\": \"/1/3/15/\", \"ParentHierarchyCode\": \"/1/3/\", \"Positions\": []}"
			+ "]},"
			+ "{\"PositionID\": 14, \"PositionName\": \"Genel Muhasebe ve Raporlama Muduru\", \"Norm\": \"1\", \"TitleCode\": \"11\", \"HierarchyCode\": \"/1/3/14/\", \"ParentHierarchyCode\": \"/1/3/\", \"Positions\": ["
			+ "  {\"PositionID\": 33, \"PositionName\": \"Genel Muhasebe Kayit ve Takip Ekibi\", \"Norm\": \"1\", \"TitleCode\": \"38\", \"HierarchyCode\": \"/1/3/14/33/\", \"ParentHierarchyCode\": \"/1/3/14/\", \"Positions\": []},"
			+ "  {\"PositionID\": 34, \"PositionName\": \"Mali Tablolar ve Konsolidasyon Ekibi\", \"Norm\": \"1\", \"TitleCode\": \"38\", \"HierarchyCode\": \"/1/3/14/34/\", \"ParentHierarchyCode\": \"/1/3/14/\", \"Positions\": []}"
			+ "]},"
			+ "{\"PositionID\": 33, \"PositionName\": \"Genel Muhasebe Kayit ve Takip Ekibi\", \"Norm\": \"1\", \"TitleCode\": \"38\", \"HierarchyCode\": \"/1/3/14/33/\", \"ParentHierarchyCode\": \"/1/3/14/\", \"Positions\": ["
			+ "  {\"PositionID\": 200, \"PositionName\": \"Kıdemli Muhasebe ve Finansal Kayit Uzmani\", \"Norm\": \"5\", \"TitleCode\": \"38\", \"HierarchyCode\": \"/1/3/14/33/200/\", \"ParentHierarchyCode\": \"/1/3/14/33/\", \"Positions\": []},"
			+ "  {\"PositionID\": 201, \"PositionName\": \"Muhasebe Kayit ve Mutabakat Uzmani\", \"Norm\": \"4\", \"TitleCode\": \"38\", \"HierarchyCode\": \"/1/3/14/33/201/\", \"ParentHierarchyCode\": \"/1/3/14/33/\", \"Positions\": []}"
			+ "]},"
			+ "{\"PositionID\": 15, \"PositionName\": \"Odeme Sistemleri ve Nakit Yonetimi Muduru\", \"Norm\": \"1\", \"TitleCode\": \"11\", \"HierarchyCode\": \"/1/3/15/\", \"ParentHierarchyCode\": \"/1/3/\", \"Positions\": ["
			+ "  {\"PositionID\": 35, \"PositionName\": \"Toplu Odeme ve Havale Islemleri Uzmani\", \"Norm\": \"6\", \"TitleCode\": \"38\", \"HierarchyCode\": \"/1/3/15/35/\", \"ParentHierarchyCode\": \"/1/3/15/\", \"Positions\": []},"
			+ "  {\"PositionID\": 36, \"PositionName\": \"Nakit Akisi ve Likidite Yonetimi Uzmani\", \"Norm\": \"4\", \"TitleCode\": \"38\", \"HierarchyCode\": \"/1/3/15/36/\", \"ParentHierarchyCode\": \"/1/3/15/\", \"Positions\": []},"
			+ "  {\"PositionID\": 37, \"PositionName\": \"Uluslararasi Odeme ve SWIFT Islemleri Uzmani\", \"Norm\": \"3\", \"TitleCode\": \"38\", \"HierarchyCode\": \"/1/3/15/37/\", \"ParentHierarchyCode\": \"/1/3/15/\", \"Positions\": []}"
			+ "]},"
			+ "{\"PositionID\": 4, \"PositionName\": \"Operasyon ve Surecler Yonetimi Direktoru\", \"Norm\": \"1\", \"TitleCode\": \"12\", \"HierarchyCode\": \"/1/4/\", \"ParentHierarchyCode\": \"/1/\", \"Positions\": ["
			+ "  {\"PositionID\": 18, \"PositionName\": \"Sube Operasyonlari ve Bolge Koordinasyon Muduru\", \"Norm\": \"1\", \"TitleCode\": \"1\", \"HierarchyCode\": \"/1/4/18/\", \"ParentHierarchyCode\": \"/1/4/\", \"Positions\": []},"
			+ "  {\"PositionID\": 19, \"PositionName\": \"Musteri Hizmetleri ve Deneyim Yonetimi Muduru\", \"Norm\": \"1\", \"TitleCode\": \"1\", \"HierarchyCode\": \"/1/4/19/\", \"ParentHierarchyCode\": \"/1/4/\", \"Positions\": []}"
			+ "]},"
			+ "{\"PositionID\": 18, \"PositionName\": \"Sube Operasyonlari ve Bolge Koordinasyon Muduru\", \"Norm\": \"1\", \"TitleCode\": \"1\", \"HierarchyCode\": \"/1/4/18/\", \"ParentHierarchyCode\": \"/1/4/\", \"Positions\": ["
			+ "  {\"PositionID\": 43, \"PositionName\": \"Istanbul Anadolu Yakasi Bolge Operasyon Muduru\", \"Norm\": \"4\", \"TitleCode\": \"37\", \"HierarchyCode\": \"/1/4/18/43/\", \"ParentHierarchyCode\": \"/1/4/18/\", \"Positions\": []},"
			+ "  {\"PositionID\": 44, \"PositionName\": \"Istanbul Avrupa Yakasi Bolge Operasyon Muduru\", \"Norm\": \"4\", \"TitleCode\": \"37\", \"HierarchyCode\": \"/1/4/18/44/\", \"ParentHierarchyCode\": \"/1/4/18/\", \"Positions\": []},"
			+ "  {\"PositionID\": 45, \"PositionName\": \"Ankara ve Ic Anadolu Bolge Operasyon Muduru\", \"Norm\": \"3\", \"TitleCode\": \"37\", \"HierarchyCode\": \"/1/4/18/45/\", \"ParentHierarchyCode\": \"/1/4/18/\", \"Positions\": []}"
			+ "]},"
			+ "{\"PositionID\": 19, \"PositionName\": \"Musteri Hizmetleri ve Deneyim Yonetimi Muduru\", \"Norm\": \"1\", \"TitleCode\": \"1\", \"HierarchyCode\": \"/1/4/19/\", \"ParentHierarchyCode\": \"/1/4/\", \"Positions\": ["
			+ "  {\"PositionID\": 48, \"PositionName\": \"Cagri Merkezi ve Telefon Bankaciligi Uzmani\", \"Norm\": \"6\", \"TitleCode\": \"4\", \"HierarchyCode\": \"/1/4/19/48/\", \"ParentHierarchyCode\": \"/1/4/19/\", \"Positions\": []},"
			+ "  {\"PositionID\": 49, \"PositionName\": \"Dijital Kanallar ve E-Musteri Hizmetleri Uzmani\", \"Norm\": \"5\", \"TitleCode\": \"4\", \"HierarchyCode\": \"/1/4/19/49/\", \"ParentHierarchyCode\": \"/1/4/19/\", \"Positions\": []},"
			+ "  {\"PositionID\": 50, \"PositionName\": \"Musteri Sikayet Yonetimi ve Cozum Uzmani\", \"Norm\": \"4\", \"TitleCode\": \"4\", \"HierarchyCode\": \"/1/4/19/50/\", \"ParentHierarchyCode\": \"/1/4/19/\", \"Positions\": []}"
			+ "]},"
			+ "{\"PositionID\": 5, \"PositionName\": \"Insan Kaynaklari ve Kurumsal Gelisim Direktoru\", \"Norm\": \"1\", \"TitleCode\": \"12\", \"HierarchyCode\": \"/1/5/\", \"ParentHierarchyCode\": \"/1/\", \"Positions\": ["
			+ "  {\"PositionID\": 55, \"PositionName\": \"Yetenek Kazanimi ve Ise Alim Yonetimi Muduru\", \"Norm\": \"1\", \"TitleCode\": \"11\", \"HierarchyCode\": \"/1/5/55/\", \"ParentHierarchyCode\": \"/1/5/\", \"Positions\": []},"
			+ "  {\"PositionID\": 56, \"PositionName\": \"Organizasyonel Gelisim ve Yetenek Yonetimi Muduru\", \"Norm\": \"1\", \"TitleCode\": \"11\", \"HierarchyCode\": \"/1/5/56/\", \"ParentHierarchyCode\": \"/1/5/\", \"Positions\": []}"
			+ "]},"
			+ "{\"PositionID\": 55, \"PositionName\": \"Yetenek Kazanimi ve Ise Alim Yonetimi Muduru\", \"Norm\": \"1\", \"TitleCode\": \"11\", \"HierarchyCode\": \"/1/5/55/\", \"ParentHierarchyCode\": \"/1/5/\", \"Positions\": ["
			+ "  {\"PositionID\": 60, \"PositionName\": \"Kurumsal Ise Alim ve Aday Degerlendirme Uzmani\", \"Norm\": \"5\", \"TitleCode\": \"38\", \"HierarchyCode\": \"/1/5/55/60/\", \"ParentHierarchyCode\": \"/1/5/55/\", \"Positions\": []},"
			+ "  {\"PositionID\": 61, \"PositionName\": \"Stajyer ve Yeni Mezun Programlari Koordinatoru\", \"Norm\": \"3\", \"TitleCode\": \"38\", \"HierarchyCode\": \"/1/5/55/61/\", \"ParentHierarchyCode\": \"/1/5/55/\", \"Positions\": []},"
			+ "  {\"PositionID\": 62, \"PositionName\": \"Ise Alim Surecleri ve Aday Deneyimi Uzmani\", \"Norm\": \"2\", \"TitleCode\": \"38\", \"HierarchyCode\": \"/1/5/55/62/\", \"ParentHierarchyCode\": \"/1/5/55/\", \"Positions\": []}"
			+ "]},"
			+ "{\"PositionID\": 56, \"PositionName\": \"Organizasyonel Gelisim ve Yetenek Yonetimi Muduru\", \"Norm\": \"1\", \"TitleCode\": \"11\", \"HierarchyCode\": \"/1/5/56/\", \"ParentHierarchyCode\": \"/1/5/\", \"Positions\": ["
			+ "  {\"PositionID\": 63, \"PositionName\": \"Egitim Programlari ve Gelisim Planlama Uzmani\", \"Norm\": \"4\", \"TitleCode\": \"38\", \"HierarchyCode\": \"/1/5/56/63/\", \"ParentHierarchyCode\": \"/1/5/56/\", \"Positions\": []},"
			+ "  {\"PositionID\": 64, \"PositionName\": \"Liderlik Gelisimi ve Yonetici Koclugu Uzmani\", \"Norm\": \"3\", \"TitleCode\": \"38\", \"HierarchyCode\": \"/1/5/56/64/\", \"ParentHierarchyCode\": \"/1/5/56/\", \"Positions\": []},"
			+ "  {\"PositionID\": 65, \"PositionName\": \"Performans Yonetimi ve Degerlendirme Sistemleri Uzmani\", \"Norm\": \"3\", \"TitleCode\": \"38\", \"HierarchyCode\": \"/1/5/56/65/\", \"ParentHierarchyCode\": \"/1/5/56/\", \"Positions\": []}"
			+ "]}"
			+ "]";
		
		// DUMMY DATA - English version (simplified for testing)
		String dummyJsonEN = "["
			+ "{\"PositionID\": 1, \"PositionName\": \"Chief Executive Officer and General Manager\", \"Norm\": \"1\", \"TitleCode\": \"9\", \"HierarchyCode\": \"/1/\", \"ParentHierarchyCode\": \"\", \"Positions\": ["
			+ "  {\"PositionID\": 2, \"PositionName\": \"Information Technology Director\", \"Norm\": \"1\", \"TitleCode\": \"12\", \"HierarchyCode\": \"/1/2/\", \"ParentHierarchyCode\": \"/1/\", \"Positions\": []},"
			+ "  {\"PositionID\": 3, \"PositionName\": \"Finance Director\", \"Norm\": \"1\", \"TitleCode\": \"12\", \"HierarchyCode\": \"/1/3/\", \"ParentHierarchyCode\": \"/1/\", \"Positions\": []}"
			+ "]},"
			+ "{\"PositionID\": 2, \"PositionName\": \"Information Technology Director\", \"Norm\": \"1\", \"TitleCode\": \"12\", \"HierarchyCode\": \"/1/2/\", \"ParentHierarchyCode\": \"/1/\", \"Positions\": ["
			+ "  {\"PositionID\": 10, \"PositionName\": \"Software Development Manager\", \"Norm\": \"1\", \"TitleCode\": \"13\", \"HierarchyCode\": \"/1/2/10/\", \"ParentHierarchyCode\": \"/1/2/\", \"Positions\": []}"
			+ "]},"
			+ "{\"PositionID\": 10, \"PositionName\": \"Software Development Manager\", \"Norm\": \"1\", \"TitleCode\": \"13\", \"HierarchyCode\": \"/1/2/10/\", \"ParentHierarchyCode\": \"/1/2/\", \"Positions\": ["
			+ "  {\"PositionID\": 100, \"PositionName\": \"Senior Backend Developer\", \"Norm\": \"4\", \"TitleCode\": \"40\", \"HierarchyCode\": \"/1/2/10/100/\", \"ParentHierarchyCode\": \"/1/2/10/\", \"Positions\": []},"
			+ "  {\"PositionID\": 101, \"PositionName\": \"Junior Backend Developer\", \"Norm\": \"6\", \"TitleCode\": \"40\", \"HierarchyCode\": \"/1/2/10/101/\", \"ParentHierarchyCode\": \"/1/2/10/\", \"Positions\": []}"
			+ "]},"
			+ "{\"PositionID\": 3, \"PositionName\": \"Finance Director\", \"Norm\": \"1\", \"TitleCode\": \"12\", \"HierarchyCode\": \"/1/3/\", \"ParentHierarchyCode\": \"/1/\", \"Positions\": ["
			+ "  {\"PositionID\": 14, \"PositionName\": \"Accounting Manager\", \"Norm\": \"1\", \"TitleCode\": \"11\", \"HierarchyCode\": \"/1/3/14/\", \"ParentHierarchyCode\": \"/1/3/\", \"Positions\": []}"
			+ "]},"
			+ "{\"PositionID\": 14, \"PositionName\": \"Accounting Manager\", \"Norm\": \"1\", \"TitleCode\": \"11\", \"HierarchyCode\": \"/1/3/14/\", \"ParentHierarchyCode\": \"/1/3/\", \"Positions\": ["
			+ "  {\"PositionID\": 200, \"PositionName\": \"Senior Accountant\", \"Norm\": \"5\", \"TitleCode\": \"38\", \"HierarchyCode\": \"/1/3/14/200/\", \"ParentHierarchyCode\": \"/1/3/14/\", \"Positions\": []},"
			+ "  {\"PositionID\": 201, \"PositionName\": \"Junior Accountant\", \"Norm\": \"4\", \"TitleCode\": \"38\", \"HierarchyCode\": \"/1/3/14/201/\", \"ParentHierarchyCode\": \"/1/3/14/\", \"Positions\": []}"
			+ "]}"
			+ "]";
		jsonEN = dummyJsonEN;
			}
			
			// Parse JSON data
			Position dataTR = null;
			Position dataEN = null;
			
			if (jsonTR != null && !jsonTR.trim().isEmpty()) {
				Core.getLogger("PDFRenderer").info("Parsing Turkish JSON data...");
				dataTR = OrgChartParser.parse(jsonTR);
			}
			
			if (jsonEN != null && !jsonEN.trim().isEmpty()) {
				Core.getLogger("PDFRenderer").info("Parsing English JSON data...");
				dataEN = OrgChartParser.parse(jsonEN);
			}
			
			if (dataTR == null && dataEN == null) {
				throw new IllegalArgumentException("At least one of TR or EN JSON data must be provided");
			}
			
			// Create renderer
			OrgChartRenderer renderer = new OrgChartRenderer();
			
			// Use parameters from constructor (with fallback defaults if null/empty)
			String titleTR = (this.titleTR != null && !this.titleTR.trim().isEmpty()) ? this.titleTR : "Organizasyon Semasi";
			String totalNormLabelTR = (this.totalNormLabelTR != null && !this.totalNormLabelTR.trim().isEmpty()) ? this.totalNormLabelTR : "Toplam Norm:";
			String preparedByTR = (this.preparedByTR != null && !this.preparedByTR.trim().isEmpty()) ? this.preparedByTR : "Hazirlayan: Organizasyon ve Surec Gelisim Mudurlugu";
			String docDateTR = (this.docDateTR != null && !this.docDateTR.trim().isEmpty()) ? this.docDateTR : "Dokuman Tarihi: Kasim 2025";
			String lastUpdateTR = (this.lastUpdateTR != null && !this.lastUpdateTR.trim().isEmpty()) ? this.lastUpdateTR : "Son Guncelleme: Kasim 2025";
			String imageUrlTR = (this.imageUrlTR != null && !this.imageUrlTR.trim().isEmpty()) ? this.imageUrlTR : "https://fintechtime.com/wp-content/uploads/2019/04/GarantiBBVA-logo.jpg";
			
			String titleEN = (this.titleEN != null && !this.titleEN.trim().isEmpty()) ? this.titleEN : "Organization Chart";
			String totalNormLabelEN = (this.totalNormLabelEN != null && !this.totalNormLabelEN.trim().isEmpty()) ? this.totalNormLabelEN : "Total Norm:";
			String preparedByEN = (this.preparedByEN != null && !this.preparedByEN.trim().isEmpty()) ? this.preparedByEN : "Prepared by: Organization and Process Development Directorate";
			String docDateEN = (this.docDateEN != null && !this.docDateEN.trim().isEmpty()) ? this.docDateEN : "Document Date: November 2025";
			String lastUpdateEN = (this.lastUpdateEN != null && !this.lastUpdateEN.trim().isEmpty()) ? this.lastUpdateEN : "Last Update: November 2025";
			String imageUrlEN = (this.imageUrlEN != null && !this.imageUrlEN.trim().isEmpty()) ? this.imageUrlEN : "https://fintechtime.com/wp-content/uploads/2019/04/GarantiBBVA-logo.jpg";
			
			// Render PDF (TR and/or EN pages)
			byte[] pdfBytes = renderer.render(
				dataTR, titleTR, totalNormLabelTR, preparedByTR, docDateTR, lastUpdateTR, imageUrlTR,
				dataEN, titleEN, totalNormLabelEN, preparedByEN, docDateEN, lastUpdateEN, imageUrlEN
			);
			
			// Convert to Base64
			String base64Pdf = Base64.getEncoder().encodeToString(pdfBytes);
			
			Core.getLogger("PDFRenderer").info("PDF generated successfully! Size: " + pdfBytes.length + " bytes");
			Core.getLogger("PDFRenderer").info("Base64 length: " + base64Pdf.length() + " chars");
			
			return base64Pdf;
			
		} catch (Exception e) {
			Core.getLogger("PDFRenderer").error("Error generating PDF: " + e.getMessage(), e);
			e.printStackTrace();
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Failed to generate PDF: " + e.getMessage(), e);
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PDFRenderer";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
