// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.core.Core;
import myfirstmodule.pdf.Position;
import myfirstmodule.pdf.OrgChartParser;
import myfirstmodule.pdf.OrgChartRenderer;
import java.util.Base64;

public class PDFRenderer extends CustomJavaAction<java.lang.String>
{
	private java.lang.String OrgJSON_TR;
	private java.lang.String OrgJSON_EN;
	private java.lang.String titleTR;
	private java.lang.String totalNormLabelTR;
	private java.lang.String preparedByTR;
	private java.lang.String docDateTR;
	private java.lang.String lastUpdateTR;
	private java.lang.String imageUrlTR;
	private java.lang.String titleEN;
	private java.lang.String totalNormLabelEN;
	private java.lang.String preparedByEN;
	private java.lang.String docDateEN;
	private java.lang.String lastUpdateEN;
	private java.lang.String imageUrlEN;

	public PDFRenderer(IContext context, java.lang.String OrgJSON_TR, java.lang.String OrgJSON_EN, java.lang.String titleTR, java.lang.String totalNormLabelTR, java.lang.String preparedByTR, java.lang.String docDateTR, java.lang.String lastUpdateTR, java.lang.String imageUrlTR, java.lang.String titleEN, java.lang.String totalNormLabelEN, java.lang.String preparedByEN, java.lang.String docDateEN, java.lang.String lastUpdateEN, java.lang.String imageUrlEN)
	{
		super(context);
		this.OrgJSON_TR = OrgJSON_TR;
		this.OrgJSON_EN = OrgJSON_EN;
		this.titleTR = titleTR;
		this.totalNormLabelTR = totalNormLabelTR;
		this.preparedByTR = preparedByTR;
		this.docDateTR = docDateTR;
		this.lastUpdateTR = lastUpdateTR;
		this.imageUrlTR = imageUrlTR;
		this.titleEN = titleEN;
		this.totalNormLabelEN = totalNormLabelEN;
		this.preparedByEN = preparedByEN;
		this.docDateEN = docDateEN;
		this.lastUpdateEN = lastUpdateEN;
		this.imageUrlEN = imageUrlEN;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			Core.getLogger("PDFRenderer").info("Starting PDF generation with provided JSON data...");
			
			// Use parameters instead of dummy data
			String jsonTR = this.OrgJSON_TR;
			String jsonEN = this.OrgJSON_EN;
			
			// Legacy dummy fallback for testing (remove in production)
			if ((jsonTR == null || jsonTR.trim().isEmpty()) && (jsonEN == null || jsonEN.trim().isEmpty())) {
				Core.getLogger("PDFRenderer").warn("No JSON data provided, using dummy test data...");
				jsonTR = "{"
			+ "\"PositionID\": 1,"
			+ "\"PositionName\": \"Icra Kurulu Baskani ve Genel Mudur\","
			+ "\"Norm\": 1,"
			+ "\"TitleCode\": \"9\","
			+ "\"Positions\": ["
			
			// IT Department - 28 nodes with long titles
			+ "  {\"PositionID\": 2, \"PositionName\": \"Bilgi Teknolojileri ve Dijital Donusum Direktoru\", \"Norm\": 1, \"TitleCode\": \"12\","
			+ "    \"Positions\": ["
			+ "      {\"PositionID\": 10, \"PositionName\": \"Kurumsal Yazilim Gelistirme ve Uygulama Muduru\", \"Norm\": 1, \"TitleCode\": \"13\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 20, \"PositionName\": \"Backend Sistemler ve API Gelistirme Takimi\", \"Norm\": 1, \"TitleCode\": \"40\","
			+ "            \"Positions\": ["
			+ "              {\"PositionID\": 100, \"PositionName\": \"Kıdemli Backend Yazilim Gelistirme Uzmani\", \"Norm\": 4, \"TitleCode\": \"40\", \"Positions\": []},"
			+ "              {\"PositionID\": 101, \"PositionName\": \"Junior Backend Yazilim Gelistirme Uzmani\", \"Norm\": 6, \"TitleCode\": \"40\", \"Positions\": []},"
			+ "              {\"PositionID\": 102, \"PositionName\": \"DevOps ve Surekli Entegrasyon Uzmani\", \"Norm\": 3, \"TitleCode\": \"40\", \"Positions\": []}"
			+ "            ]"
			+ "          },"
			+ "          {\"PositionID\": 21, \"PositionName\": \"Frontend ve Kullanici Deneyimi Takimi\", \"Norm\": 1, \"TitleCode\": \"40\","
			+ "            \"Positions\": ["
			+ "              {\"PositionID\": 103, \"PositionName\": \"Kıdemli Frontend Gelistirici ve React Uzmani\", \"Norm\": 3, \"TitleCode\": \"40\", \"Positions\": []},"
			+ "              {\"PositionID\": 104, \"PositionName\": \"Kullanici Arayuzu ve Deneyim Tasarim Uzmani\", \"Norm\": 2, \"TitleCode\": \"40\", \"Positions\": []},"
			+ "              {\"PositionID\": 105, \"PositionName\": \"Erisebilirlik ve Performans Optimizasyonu Uzmani\", \"Norm\": 2, \"TitleCode\": \"40\", \"Positions\": []}"
			+ "            ]"
			+ "          },"
			+ "          {\"PositionID\": 22, \"PositionName\": \"Mobil Uygulama Gelistirme ve Platform Takimi\", \"Norm\": 1, \"TitleCode\": \"40\","
			+ "            \"Positions\": ["
			+ "              {\"PositionID\": 106, \"PositionName\": \"iOS Mobil Uygulama Gelistirme Uzmani\", \"Norm\": 3, \"TitleCode\": \"40\", \"Positions\": []},"
			+ "              {\"PositionID\": 107, \"PositionName\": \"Android Mobil Uygulama Gelistirme Uzmani\", \"Norm\": 3, \"TitleCode\": \"40\", \"Positions\": []},"
			+ "              {\"PositionID\": 108, \"PositionName\": \"Cross-Platform ve Hibrit Uygulama Uzmani\", \"Norm\": 2, \"TitleCode\": \"40\", \"Positions\": []}"
			+ "            ]"
			+ "          }"
			+ "        ]"
			+ "      },"
			+ "      {\"PositionID\": 11, \"PositionName\": \"Sistem Altyapisi ve Bulut Teknolojileri Muduru\", \"Norm\": 1, \"TitleCode\": \"13\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 23, \"PositionName\": \"Ag Altyapisi ve Iletisim Sistemleri Uzmani\", \"Norm\": 5, \"TitleCode\": \"39\", \"Positions\": []},"
			+ "          {\"PositionID\": 24, \"PositionName\": \"Bulut Mimarisi ve Azure Platform Uzmani\", \"Norm\": 4, \"TitleCode\": \"39\", \"Positions\": []},"
			+ "          {\"PositionID\": 25, \"PositionName\": \"Veritabani Yonetimi ve Optimizasyon Uzmani\", \"Norm\": 4, \"TitleCode\": \"39\", \"Positions\": []},"
			+ "          {\"PositionID\": 26, \"PositionName\": \"Sunucu ve Sanallaştirma Teknolojileri Uzmani\", \"Norm\": 3, \"TitleCode\": \"39\", \"Positions\": []}"
			+ "        ]"
			+ "      },"
			+ "      {\"PositionID\": 12, \"PositionName\": \"Bilgi Guvenligi ve Siber Savunma Muduru\", \"Norm\": 1, \"TitleCode\": \"13\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 27, \"PositionName\": \"Siber Guvenlik Tehdit Analizi Uzmani\", \"Norm\": 4, \"TitleCode\": \"39\", \"Positions\": []},"
			+ "          {\"PositionID\": 28, \"PositionName\": \"Uygulama Guvenligi ve Penetrasyon Testi Uzmani\", \"Norm\": 3, \"TitleCode\": \"39\", \"Positions\": []},"
			+ "          {\"PositionID\": 29, \"PositionName\": \"Guvenlik Operasyonlari ve Olay Mudahale Uzmani\", \"Norm\": 5, \"TitleCode\": \"39\", \"Positions\": []}"
			+ "        ]"
			+ "      },"
			+ "      {\"PositionID\": 13, \"PositionName\": \"Veri Analizi ve Is Zekasi Sistemleri Muduru\", \"Norm\": 1, \"TitleCode\": \"13\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 30, \"PositionName\": \"Veri Bilimi ve Makine Ogrenmesi Uzmani\", \"Norm\": 3, \"TitleCode\": \"39\", \"Positions\": []},"
			+ "          {\"PositionID\": 31, \"PositionName\": \"Is Zekasi ve Raporlama Sistemleri Uzmani\", \"Norm\": 4, \"TitleCode\": \"39\", \"Positions\": []},"
			+ "          {\"PositionID\": 32, \"PositionName\": \"Veri Ambari ve ETL Surecler Uzmani\", \"Norm\": 3, \"TitleCode\": \"39\", \"Positions\": []}"
			+ "        ]"
			+ "      }"
			+ "    ]"
			+ "  },"
			
			// Finance Department - 22 nodes
			+ "  {\"PositionID\": 3, \"PositionName\": \"Mali Isler ve Finans Yonetimi Direktoru\", \"Norm\": 1, \"TitleCode\": \"12\","
			+ "    \"Positions\": ["
			+ "      {\"PositionID\": 14, \"PositionName\": \"Genel Muhasebe ve Raporlama Muduru\", \"Norm\": 1, \"TitleCode\": \"11\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 33, \"PositionName\": \"Genel Muhasebe Kayit ve Takip Ekibi\", \"Norm\": 1, \"TitleCode\": \"38\","
			+ "            \"Positions\": ["
			+ "              {\"PositionID\": 200, \"PositionName\": \"Kıdemli Muhasebe ve Finansal Kayit Uzmani\", \"Norm\": 5, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "              {\"PositionID\": 201, \"PositionName\": \"Muhasebe Kayit ve Mutabakat Uzmani\", \"Norm\": 4, \"TitleCode\": \"38\", \"Positions\": []}"
			+ "            ]"
			+ "          },"
			+ "          {\"PositionID\": 34, \"PositionName\": \"Mali Tablolar ve Konsolidasyon Ekibi\", \"Norm\": 1, \"TitleCode\": \"38\","
			+ "            \"Positions\": ["
			+ "              {\"PositionID\": 202, \"PositionName\": \"Finansal Tablo Hazirlama ve Analiz Uzmani\", \"Norm\": 4, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "              {\"PositionID\": 203, \"PositionName\": \"Konsolidasyon ve Grup Raporlama Uzmani\", \"Norm\": 3, \"TitleCode\": \"38\", \"Positions\": []}"
			+ "            ]"
			+ "          }"
			+ "        ]"
			+ "      },"
			+ "      {\"PositionID\": 15, \"PositionName\": \"Odeme Sistemleri ve Nakit Yonetimi Muduru\", \"Norm\": 1, \"TitleCode\": \"11\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 35, \"PositionName\": \"Toplu Odeme ve Havale Islemleri Uzmani\", \"Norm\": 6, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 36, \"PositionName\": \"Nakit Akisi ve Likidite Yonetimi Uzmani\", \"Norm\": 4, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 37, \"PositionName\": \"Uluslararasi Odeme ve SWIFT Islemleri Uzmani\", \"Norm\": 3, \"TitleCode\": \"38\", \"Positions\": []}"
			+ "        ]"
			+ "      },"
			+ "      {\"PositionID\": 16, \"PositionName\": \"Butce Planlama ve Maliyet Kontrolu Muduru\", \"Norm\": 1, \"TitleCode\": \"11\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 38, \"PositionName\": \"Stratejik Butce Planlama ve Tahmin Uzmani\", \"Norm\": 5, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 39, \"PositionName\": \"Maliyet Analizi ve Performans Olcumu Uzmani\", \"Norm\": 4, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 40, \"PositionName\": \"Yatirim Butcesi ve Proje Maliyetleri Uzmani\", \"Norm\": 3, \"TitleCode\": \"38\", \"Positions\": []}"
			+ "        ]"
			+ "      },"
			+ "      {\"PositionID\": 17, \"PositionName\": \"Risk Yonetimi ve Uyum Muduru\", \"Norm\": 1, \"TitleCode\": \"11\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 41, \"PositionName\": \"Finansal Risk Analizi ve Yonetimi Uzmani\", \"Norm\": 5, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 42, \"PositionName\": \"Uyum ve Duzenleme Gereksinimleri Uzmani\", \"Norm\": 4, \"TitleCode\": \"38\", \"Positions\": []}"
			+ "        ]"
			+ "      }"
			+ "    ]"
			+ "  },"
			
			// Operations Department - 18 nodes
			+ "  {\"PositionID\": 4, \"PositionName\": \"Operasyon ve Surecler Yonetimi Direktoru\", \"Norm\": 1, \"TitleCode\": \"12\","
			+ "    \"Positions\": ["
			+ "      {\"PositionID\": 18, \"PositionName\": \"Sube Operasyonlari ve Bolge Koordinasyon Muduru\", \"Norm\": 1, \"TitleCode\": \"1\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 43, \"PositionName\": \"Istanbul Anadolu Yakasi Bolge Operasyon Muduru\", \"Norm\": 4, \"TitleCode\": \"37\", \"Positions\": []},"
			+ "          {\"PositionID\": 44, \"PositionName\": \"Istanbul Avrupa Yakasi Bolge Operasyon Muduru\", \"Norm\": 4, \"TitleCode\": \"37\", \"Positions\": []},"
			+ "          {\"PositionID\": 45, \"PositionName\": \"Ankara ve Ic Anadolu Bolge Operasyon Muduru\", \"Norm\": 3, \"TitleCode\": \"37\", \"Positions\": []},"
			+ "          {\"PositionID\": 46, \"PositionName\": \"Ege ve Akdeniz Bolge Operasyon Muduru\", \"Norm\": 3, \"TitleCode\": \"37\", \"Positions\": []},"
			+ "          {\"PositionID\": 47, \"PositionName\": \"Karadeniz ve Dogu Anadolu Bolge Operasyon Muduru\", \"Norm\": 2, \"TitleCode\": \"37\", \"Positions\": []}"
			+ "        ]"
			+ "      },"
			+ "      {\"PositionID\": 19, \"PositionName\": \"Musteri Hizmetleri ve Deneyim Yonetimi Muduru\", \"Norm\": 1, \"TitleCode\": \"1\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 48, \"PositionName\": \"Cagri Merkezi ve Telefon Bankaciligi Uzmani\", \"Norm\": 6, \"TitleCode\": \"4\", \"Positions\": []},"
			+ "          {\"PositionID\": 49, \"PositionName\": \"Dijital Kanallar ve E-Musteri Hizmetleri Uzmani\", \"Norm\": 5, \"TitleCode\": \"4\", \"Positions\": []},"
			+ "          {\"PositionID\": 50, \"PositionName\": \"Musteri Sikayet Yonetimi ve Cozum Uzmani\", \"Norm\": 4, \"TitleCode\": \"4\", \"Positions\": []},"
			+ "          {\"PositionID\": 51, \"PositionName\": \"Musteri Memnuniyeti Olcumu ve Analiz Uzmani\", \"Norm\": 3, \"TitleCode\": \"4\", \"Positions\": []}"
			+ "        ]"
			+ "      },"
			+ "      {\"PositionID\": 52, \"PositionName\": \"Surecler ve Kalite Yonetimi Muduru\", \"Norm\": 1, \"TitleCode\": \"1\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 53, \"PositionName\": \"Is Surecleri Iyilestirme ve Optimize Etme Uzmani\", \"Norm\": 4, \"TitleCode\": \"4\", \"Positions\": []},"
			+ "          {\"PositionID\": 54, \"PositionName\": \"Kalite Guvencesi ve Standartlar Uyum Uzmani\", \"Norm\": 3, \"TitleCode\": \"4\", \"Positions\": []}"
			+ "        ]"
			+ "      }"
			+ "    ]"
			+ "  },"
			
			// HR Department - 16 nodes
			+ "  {\"PositionID\": 5, \"PositionName\": \"Insan Kaynaklari ve Kurumsal Gelisim Direktoru\", \"Norm\": 1, \"TitleCode\": \"12\","
			+ "    \"Positions\": ["
			+ "      {\"PositionID\": 55, \"PositionName\": \"Yetenek Kazanimi ve Ise Alim Yonetimi Muduru\", \"Norm\": 1, \"TitleCode\": \"11\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 60, \"PositionName\": \"Kurumsal Ise Alim ve Aday Degerlendirme Uzmani\", \"Norm\": 5, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 61, \"PositionName\": \"Stajyer ve Yeni Mezun Programlari Koordinatoru\", \"Norm\": 3, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 62, \"PositionName\": \"Ise Alim Surecleri ve Aday Deneyimi Uzmani\", \"Norm\": 2, \"TitleCode\": \"38\", \"Positions\": []}"
			+ "        ]"
			+ "      },"
			+ "      {\"PositionID\": 56, \"PositionName\": \"Organizasyonel Gelisim ve Yetenek Yonetimi Muduru\", \"Norm\": 1, \"TitleCode\": \"11\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 63, \"PositionName\": \"Egitim Programlari ve Gelisim Planlama Uzmani\", \"Norm\": 4, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 64, \"PositionName\": \"Liderlik Gelisimi ve Yonetici Koclugu Uzmani\", \"Norm\": 3, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 65, \"PositionName\": \"Performans Yonetimi ve Degerlendirme Sistemleri Uzmani\", \"Norm\": 3, \"TitleCode\": \"38\", \"Positions\": []}"
			+ "        ]"
			+ "      },"
			+ "      {\"PositionID\": 57, \"PositionName\": \"Ucret Yonetimi ve Personel Hizmetleri Muduru\", \"Norm\": 1, \"TitleCode\": \"11\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 66, \"PositionName\": \"Bordro Islemleri ve Maas Yonetimi Uzmani\", \"Norm\": 4, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 67, \"PositionName\": \"Yan Haklar ve Sosyal Faydalar Yonetimi Uzmani\", \"Norm\": 3, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 68, \"PositionName\": \"Ozluk Islemleri ve Personel Dosya Yonetimi Uzmani\", \"Norm\": 3, \"TitleCode\": \"38\", \"Positions\": []}"
			+ "        ]"
			+ "      },"
			+ "      {\"PositionID\": 58, \"PositionName\": \"Calisan Iliskileri ve Ic Iletisim Muduru\", \"Norm\": 1, \"TitleCode\": \"11\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 69, \"PositionName\": \"Calisan Bagliligi ve Memnuniyet Programlari Uzmani\", \"Norm\": 4, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 70, \"PositionName\": \"Kurumsal Iletisim ve Etkinlik Yonetimi Uzmani\", \"Norm\": 3, \"TitleCode\": \"38\", \"Positions\": []}"
			+ "        ]"
			+ "      }"
			+ "    ]"
			+ "  }"
		+ "]"
		+ "}";
		
		// DUMMY DATA - English version (identical structure)
		String dummyJsonEN = "{"
			+ "\"PositionID\": 1,"
			+ "\"PositionName\": \"Chief Executive Officer and General Manager\","
			+ "\"Norm\": 1,"
			+ "\"TitleCode\": \"9\","
			+ "\"Positions\": ["
			
			// IT Department - English
			+ "  {\"PositionID\": 2, \"PositionName\": \"Information Technology and Digital Transformation Director\", \"Norm\": 1, \"TitleCode\": \"12\","
			+ "    \"Positions\": ["
			+ "      {\"PositionID\": 10, \"PositionName\": \"Enterprise Software Development and Application Manager\", \"Norm\": 1, \"TitleCode\": \"13\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 20, \"PositionName\": \"Backend Systems and API Development Team\", \"Norm\": 1, \"TitleCode\": \"40\","
			+ "            \"Positions\": ["
			+ "              {\"PositionID\": 100, \"PositionName\": \"Senior Backend Software Development Specialist\", \"Norm\": 4, \"TitleCode\": \"40\", \"Positions\": []},"
			+ "              {\"PositionID\": 101, \"PositionName\": \"Junior Backend Software Development Specialist\", \"Norm\": 6, \"TitleCode\": \"40\", \"Positions\": []},"
			+ "              {\"PositionID\": 102, \"PositionName\": \"DevOps and Continuous Integration Specialist\", \"Norm\": 3, \"TitleCode\": \"40\", \"Positions\": []}"
			+ "            ]"
			+ "          },"
			+ "          {\"PositionID\": 21, \"PositionName\": \"Frontend and User Experience Team\", \"Norm\": 1, \"TitleCode\": \"40\","
			+ "            \"Positions\": ["
			+ "              {\"PositionID\": 103, \"PositionName\": \"Senior Frontend Developer and React Specialist\", \"Norm\": 3, \"TitleCode\": \"40\", \"Positions\": []},"
			+ "              {\"PositionID\": 104, \"PositionName\": \"User Interface and Experience Design Specialist\", \"Norm\": 2, \"TitleCode\": \"40\", \"Positions\": []},"
			+ "              {\"PositionID\": 105, \"PositionName\": \"Accessibility and Performance Optimization Specialist\", \"Norm\": 2, \"TitleCode\": \"40\", \"Positions\": []}"
			+ "            ]"
			+ "          },"
			+ "          {\"PositionID\": 22, \"PositionName\": \"Mobile Application Development and Platform Team\", \"Norm\": 1, \"TitleCode\": \"40\","
			+ "            \"Positions\": ["
			+ "              {\"PositionID\": 106, \"PositionName\": \"iOS Mobile Application Development Specialist\", \"Norm\": 3, \"TitleCode\": \"40\", \"Positions\": []},"
			+ "              {\"PositionID\": 107, \"PositionName\": \"Android Mobile Application Development Specialist\", \"Norm\": 3, \"TitleCode\": \"40\", \"Positions\": []},"
			+ "              {\"PositionID\": 108, \"PositionName\": \"Cross-Platform and Hybrid Application Specialist\", \"Norm\": 2, \"TitleCode\": \"40\", \"Positions\": []}"
			+ "            ]"
			+ "          }"
			+ "        ]"
			+ "      },"
			+ "      {\"PositionID\": 11, \"PositionName\": \"System Infrastructure and Cloud Technologies Manager\", \"Norm\": 1, \"TitleCode\": \"13\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 23, \"PositionName\": \"Network Infrastructure and Communication Systems Specialist\", \"Norm\": 5, \"TitleCode\": \"39\", \"Positions\": []},"
			+ "          {\"PositionID\": 24, \"PositionName\": \"Cloud Architecture and Azure Platform Specialist\", \"Norm\": 4, \"TitleCode\": \"39\", \"Positions\": []},"
			+ "          {\"PositionID\": 25, \"PositionName\": \"Database Management and Optimization Specialist\", \"Norm\": 4, \"TitleCode\": \"39\", \"Positions\": []},"
			+ "          {\"PositionID\": 26, \"PositionName\": \"Server and Virtualization Technologies Specialist\", \"Norm\": 3, \"TitleCode\": \"39\", \"Positions\": []}"
			+ "        ]"
			+ "      },"
			+ "      {\"PositionID\": 12, \"PositionName\": \"Information Security and Cyber Defense Manager\", \"Norm\": 1, \"TitleCode\": \"13\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 27, \"PositionName\": \"Cyber Security Threat Analysis Specialist\", \"Norm\": 4, \"TitleCode\": \"39\", \"Positions\": []},"
			+ "          {\"PositionID\": 28, \"PositionName\": \"Application Security and Penetration Testing Specialist\", \"Norm\": 3, \"TitleCode\": \"39\", \"Positions\": []},"
			+ "          {\"PositionID\": 29, \"PositionName\": \"Security Operations and Incident Response Specialist\", \"Norm\": 5, \"TitleCode\": \"39\", \"Positions\": []}"
			+ "        ]"
			+ "      },"
			+ "      {\"PositionID\": 13, \"PositionName\": \"Data Analytics and Business Intelligence Systems Manager\", \"Norm\": 1, \"TitleCode\": \"13\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 30, \"PositionName\": \"Data Science and Machine Learning Specialist\", \"Norm\": 3, \"TitleCode\": \"39\", \"Positions\": []},"
			+ "          {\"PositionID\": 31, \"PositionName\": \"Business Intelligence and Reporting Systems Specialist\", \"Norm\": 4, \"TitleCode\": \"39\", \"Positions\": []},"
			+ "          {\"PositionID\": 32, \"PositionName\": \"Data Warehouse and ETL Processes Specialist\", \"Norm\": 3, \"TitleCode\": \"39\", \"Positions\": []}"
			+ "        ]"
			+ "      }"
			+ "    ]"
			+ "  },"
			
			// Finance Department - English
			+ "  {\"PositionID\": 3, \"PositionName\": \"Financial Affairs and Finance Management Director\", \"Norm\": 1, \"TitleCode\": \"12\","
			+ "    \"Positions\": ["
			+ "      {\"PositionID\": 14, \"PositionName\": \"General Accounting and Reporting Manager\", \"Norm\": 1, \"TitleCode\": \"11\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 33, \"PositionName\": \"General Accounting Recording and Tracking Team\", \"Norm\": 1, \"TitleCode\": \"38\","
			+ "            \"Positions\": ["
			+ "              {\"PositionID\": 200, \"PositionName\": \"Senior Accounting and Financial Recording Specialist\", \"Norm\": 5, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "              {\"PositionID\": 201, \"PositionName\": \"Accounting Recording and Reconciliation Specialist\", \"Norm\": 4, \"TitleCode\": \"38\", \"Positions\": []}"
			+ "            ]"
			+ "          },"
			+ "          {\"PositionID\": 34, \"PositionName\": \"Financial Statements and Consolidation Team\", \"Norm\": 1, \"TitleCode\": \"38\","
			+ "            \"Positions\": ["
			+ "              {\"PositionID\": 202, \"PositionName\": \"Financial Statement Preparation and Analysis Specialist\", \"Norm\": 4, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "              {\"PositionID\": 203, \"PositionName\": \"Consolidation and Group Reporting Specialist\", \"Norm\": 3, \"TitleCode\": \"38\", \"Positions\": []}"
			+ "            ]"
			+ "          }"
			+ "        ]"
			+ "      },"
			+ "      {\"PositionID\": 15, \"PositionName\": \"Payment Systems and Cash Management Manager\", \"Norm\": 1, \"TitleCode\": \"11\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 35, \"PositionName\": \"Bulk Payment and Transfer Operations Specialist\", \"Norm\": 6, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 36, \"PositionName\": \"Cash Flow and Liquidity Management Specialist\", \"Norm\": 4, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 37, \"PositionName\": \"International Payment and SWIFT Operations Specialist\", \"Norm\": 3, \"TitleCode\": \"38\", \"Positions\": []}"
			+ "        ]"
			+ "      },"
			+ "      {\"PositionID\": 16, \"PositionName\": \"Budget Planning and Cost Control Manager\", \"Norm\": 1, \"TitleCode\": \"11\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 38, \"PositionName\": \"Strategic Budget Planning and Forecasting Specialist\", \"Norm\": 5, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 39, \"PositionName\": \"Cost Analysis and Performance Measurement Specialist\", \"Norm\": 4, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 40, \"PositionName\": \"Investment Budget and Project Cost Specialist\", \"Norm\": 3, \"TitleCode\": \"38\", \"Positions\": []}"
			+ "        ]"
			+ "      },"
			+ "      {\"PositionID\": 17, \"PositionName\": \"Risk Management and Compliance Manager\", \"Norm\": 1, \"TitleCode\": \"11\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 41, \"PositionName\": \"Financial Risk Analysis and Management Specialist\", \"Norm\": 5, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 42, \"PositionName\": \"Compliance and Regulatory Requirements Specialist\", \"Norm\": 4, \"TitleCode\": \"38\", \"Positions\": []}"
			+ "        ]"
			+ "      }"
			+ "    ]"
			+ "  },"
			
			// Operations Department - English
			+ "  {\"PositionID\": 4, \"PositionName\": \"Operations and Process Management Director\", \"Norm\": 1, \"TitleCode\": \"12\","
			+ "    \"Positions\": ["
			+ "      {\"PositionID\": 18, \"PositionName\": \"Branch Operations and Regional Coordination Manager\", \"Norm\": 1, \"TitleCode\": \"1\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 43, \"PositionName\": \"Istanbul Anatolian Side Regional Operations Manager\", \"Norm\": 4, \"TitleCode\": \"37\", \"Positions\": []},"
			+ "          {\"PositionID\": 44, \"PositionName\": \"Istanbul European Side Regional Operations Manager\", \"Norm\": 4, \"TitleCode\": \"37\", \"Positions\": []},"
			+ "          {\"PositionID\": 45, \"PositionName\": \"Ankara and Central Anatolia Regional Operations Manager\", \"Norm\": 3, \"TitleCode\": \"37\", \"Positions\": []},"
			+ "          {\"PositionID\": 46, \"PositionName\": \"Aegean and Mediterranean Regional Operations Manager\", \"Norm\": 3, \"TitleCode\": \"37\", \"Positions\": []},"
			+ "          {\"PositionID\": 47, \"PositionName\": \"Black Sea and Eastern Anatolia Regional Operations Manager\", \"Norm\": 2, \"TitleCode\": \"37\", \"Positions\": []}"
			+ "        ]"
			+ "      },"
			+ "      {\"PositionID\": 19, \"PositionName\": \"Customer Services and Experience Management Manager\", \"Norm\": 1, \"TitleCode\": \"1\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 48, \"PositionName\": \"Call Center and Phone Banking Specialist\", \"Norm\": 6, \"TitleCode\": \"4\", \"Positions\": []},"
			+ "          {\"PositionID\": 49, \"PositionName\": \"Digital Channels and E-Customer Services Specialist\", \"Norm\": 5, \"TitleCode\": \"4\", \"Positions\": []},"
			+ "          {\"PositionID\": 50, \"PositionName\": \"Customer Complaint Management and Resolution Specialist\", \"Norm\": 4, \"TitleCode\": \"4\", \"Positions\": []},"
			+ "          {\"PositionID\": 51, \"PositionName\": \"Customer Satisfaction Measurement and Analysis Specialist\", \"Norm\": 3, \"TitleCode\": \"4\", \"Positions\": []}"
			+ "        ]"
			+ "      },"
			+ "      {\"PositionID\": 52, \"PositionName\": \"Process and Quality Management Manager\", \"Norm\": 1, \"TitleCode\": \"1\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 53, \"PositionName\": \"Business Process Improvement and Optimization Specialist\", \"Norm\": 4, \"TitleCode\": \"4\", \"Positions\": []},"
			+ "          {\"PositionID\": 54, \"PositionName\": \"Quality Assurance and Standards Compliance Specialist\", \"Norm\": 3, \"TitleCode\": \"4\", \"Positions\": []}"
			+ "        ]"
			+ "      }"
			+ "    ]"
			+ "  },"
			
			// HR Department - English
			+ "  {\"PositionID\": 5, \"PositionName\": \"Human Resources and Corporate Development Director\", \"Norm\": 1, \"TitleCode\": \"12\","
			+ "    \"Positions\": ["
			+ "      {\"PositionID\": 55, \"PositionName\": \"Talent Acquisition and Recruitment Management Manager\", \"Norm\": 1, \"TitleCode\": \"11\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 60, \"PositionName\": \"Corporate Recruitment and Candidate Evaluation Specialist\", \"Norm\": 5, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 61, \"PositionName\": \"Internship and Graduate Programs Coordinator\", \"Norm\": 3, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 62, \"PositionName\": \"Recruitment Processes and Candidate Experience Specialist\", \"Norm\": 2, \"TitleCode\": \"38\", \"Positions\": []}"
			+ "        ]"
			+ "      },"
			+ "      {\"PositionID\": 56, \"PositionName\": \"Organizational Development and Talent Management Manager\", \"Norm\": 1, \"TitleCode\": \"11\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 63, \"PositionName\": \"Training Programs and Development Planning Specialist\", \"Norm\": 4, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 64, \"PositionName\": \"Leadership Development and Executive Coaching Specialist\", \"Norm\": 3, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 65, \"PositionName\": \"Performance Management and Evaluation Systems Specialist\", \"Norm\": 3, \"TitleCode\": \"38\", \"Positions\": []}"
			+ "        ]"
			+ "      },"
			+ "      {\"PositionID\": 57, \"PositionName\": \"Compensation Management and Personnel Services Manager\", \"Norm\": 1, \"TitleCode\": \"11\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 66, \"PositionName\": \"Payroll Processing and Salary Management Specialist\", \"Norm\": 4, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 67, \"PositionName\": \"Benefits and Social Welfare Management Specialist\", \"Norm\": 3, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 68, \"PositionName\": \"Personnel Affairs and Employee File Management Specialist\", \"Norm\": 3, \"TitleCode\": \"38\", \"Positions\": []}"
			+ "        ]"
			+ "      },"
			+ "      {\"PositionID\": 58, \"PositionName\": \"Employee Relations and Internal Communication Manager\", \"Norm\": 1, \"TitleCode\": \"11\","
			+ "        \"Positions\": ["
			+ "          {\"PositionID\": 69, \"PositionName\": \"Employee Engagement and Satisfaction Programs Specialist\", \"Norm\": 4, \"TitleCode\": \"38\", \"Positions\": []},"
			+ "          {\"PositionID\": 70, \"PositionName\": \"Corporate Communication and Event Management Specialist\", \"Norm\": 3, \"TitleCode\": \"38\", \"Positions\": []}"
			+ "        ]"
			+ "      }"
			+ "    ]"
			+ "  }"
		+ "]"
		+ "}";
				jsonEN = "{\"PositionID\": 1, \"PositionName\": \"Chief Executive Officer\", \"Norm\": 1, \"TitleCode\": \"9\", \"Positions\": []}";
			}
			
			// Parse JSON data
			Position dataTR = null;
			Position dataEN = null;
			
			if (jsonTR != null && !jsonTR.trim().isEmpty()) {
				Core.getLogger("PDFRenderer").info("Parsing Turkish JSON data...");
				dataTR = OrgChartParser.parse(jsonTR);
			}
			
			if (jsonEN != null && !jsonEN.trim().isEmpty()) {
				Core.getLogger("PDFRenderer").info("Parsing English JSON data...");
				dataEN = OrgChartParser.parse(jsonEN);
			}
			
			if (dataTR == null && dataEN == null) {
				throw new IllegalArgumentException("At least one of TR or EN JSON data must be provided");
			}
			
			// Create renderer
			OrgChartRenderer renderer = new OrgChartRenderer();
			
			// Default parameters - Turkish (can be made into action parameters later)
			String titleTR = "Organizasyon Semasi";
			String totalNormLabelTR = "Toplam Norm:";
			String preparedByTR = "Hazirlayan: Organizasyon ve Surec Gelisim Mudurlugu";
			String docDateTR = "Dokuman Tarihi: Kasim 2025";
			String lastUpdateTR = "Son Guncelleme: Kasim 2025";
			String imageUrlTR = "https://fintechtime.com/wp-content/uploads/2019/04/GarantiBBVA-logo.jpg";
			
			// Default parameters - English (can be made into action parameters later)
			String titleEN = "Organization Chart";
			String totalNormLabelEN = "Total Norm:";
			String preparedByEN = "Prepared by: Organization and Process Development Directorate";
			String docDateEN = "Document Date: November 2025";
			String lastUpdateEN = "Last Update: November 2025";
			String imageUrlEN = "https://fintechtime.com/wp-content/uploads/2019/04/GarantiBBVA-logo.jpg";
			
			// Render PDF (TR and/or EN pages)
			byte[] pdfBytes = renderer.render(
				dataTR, titleTR, totalNormLabelTR, preparedByTR, docDateTR, lastUpdateTR, imageUrlTR,
				dataEN, titleEN, totalNormLabelEN, preparedByEN, docDateEN, lastUpdateEN, imageUrlEN
			);
			
			// Convert to Base64
			String base64Pdf = Base64.getEncoder().encodeToString(pdfBytes);
			
			Core.getLogger("PDFRenderer").info("PDF generated successfully! Size: " + pdfBytes.length + " bytes");
			Core.getLogger("PDFRenderer").info("Base64 length: " + base64Pdf.length() + " chars");
			
			return base64Pdf;
			
		} catch (Exception e) {
			Core.getLogger("PDFRenderer").error("Error generating PDF: " + e.getMessage(), e);
			e.printStackTrace();
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Failed to generate PDF: " + e.getMessage(), e);
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PDFRenderer";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
