// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.core.Core;
import myfirstmodule.pdf.Position;
import myfirstmodule.pdf.OrgChartParser;
import myfirstmodule.pdf.OrgChartRenderer;
import java.util.Base64;

public class PDFRenderer extends CustomJavaAction<java.lang.String>
{
	private java.lang.String OrgJSON_TR;
	private java.lang.String OrgJSON_EN;
	private java.lang.String titleTR;
	private java.lang.String totalNormLabelTR;
	private java.lang.String preparedByTR;
	private java.lang.String docDateTR;
	private java.lang.String lastUpdateTR;
	private java.lang.String imageUrlTR;
	private java.lang.String titleEN;
	private java.lang.String totalNormLabelEN;
	private java.lang.String preparedByEN;
	private java.lang.String docDateEN;
	private java.lang.String lastUpdateEN;
	private java.lang.String imageUrlEN;

	public PDFRenderer(IContext context, java.lang.String OrgJSON_TR, java.lang.String OrgJSON_EN, java.lang.String titleTR, java.lang.String totalNormLabelTR, java.lang.String preparedByTR, java.lang.String docDateTR, java.lang.String lastUpdateTR, java.lang.String imageUrlTR, java.lang.String titleEN, java.lang.String totalNormLabelEN, java.lang.String preparedByEN, java.lang.String docDateEN, java.lang.String lastUpdateEN, java.lang.String imageUrlEN)
	{
		super(context);
		this.OrgJSON_TR = OrgJSON_TR;
		this.OrgJSON_EN = OrgJSON_EN;
		this.titleTR = titleTR;
		this.totalNormLabelTR = totalNormLabelTR;
		this.preparedByTR = preparedByTR;
		this.docDateTR = docDateTR;
		this.lastUpdateTR = lastUpdateTR;
		this.imageUrlTR = imageUrlTR;
		this.titleEN = titleEN;
		this.totalNormLabelEN = totalNormLabelEN;
		this.preparedByEN = preparedByEN;
		this.docDateEN = docDateEN;
		this.lastUpdateEN = lastUpdateEN;
		this.imageUrlEN = imageUrlEN;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			Core.getLogger("PDFRenderer").info("Starting PDF generation with provided JSON data...");
			
			// Use parameters instead of dummy data
			String jsonTR = this.OrgJSON_TR;
			String jsonEN = this.OrgJSON_EN;
			// Parse JSON data
			Position dataTR = null;
			Position dataEN = null;
			
			if (jsonTR != null && !jsonTR.trim().isEmpty()) {
				Core.getLogger("PDFRenderer").info("Parsing Turkish JSON data...");
				dataTR = OrgChartParser.parse(jsonTR);
			}
			
			if (jsonEN != null && !jsonEN.trim().isEmpty()) {
				Core.getLogger("PDFRenderer").info("Parsing English JSON data...");
				dataEN = OrgChartParser.parse(jsonEN);
			}
			
			if (dataTR == null && dataEN == null) {
				throw new IllegalArgumentException("At least one of TR or EN JSON data must be provided");
			}
			
			// Create renderer
			OrgChartRenderer renderer = new OrgChartRenderer();
			
			// Use parameters as-is (empty means empty, no defaults)
			String titleTR = this.titleTR;
			String totalNormLabelTR = this.totalNormLabelTR;
			String preparedByTR = this.preparedByTR;
			String docDateTR = this.docDateTR;
			String lastUpdateTR = this.lastUpdateTR;
			String imageUrlTR = this.imageUrlTR;
			
			// Use parameters as-is (empty means empty, no defaults)
			String titleEN = this.titleEN;
			String totalNormLabelEN = this.totalNormLabelEN;
			String preparedByEN = this.preparedByEN;
			String docDateEN = this.docDateEN;
			String lastUpdateEN = this.lastUpdateEN;
			String imageUrlEN = this.imageUrlEN;
			
			// Render PDF (TR and/or EN pages)
			byte[] pdfBytes = renderer.render(
				dataTR, titleTR, totalNormLabelTR, preparedByTR, docDateTR, lastUpdateTR, imageUrlTR,
				dataEN, titleEN, totalNormLabelEN, preparedByEN, docDateEN, lastUpdateEN, imageUrlEN
			);
			
			// Convert to Base64
			String base64Pdf = Base64.getEncoder().encodeToString(pdfBytes);
			
			Core.getLogger("PDFRenderer").info("PDF generated successfully! Size: " + pdfBytes.length + " bytes");
			Core.getLogger("PDFRenderer").info("Base64 length: " + base64Pdf.length() + " chars");
			
			return base64Pdf;
			
		} catch (Exception e) {
			Core.getLogger("PDFRenderer").error("Error generating PDF: " + e.getMessage(), e);
			e.printStackTrace();
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Failed to generate PDF: " + e.getMessage(), e);
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PDFRenderer";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
